modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Maciej916/Ma-Enchants/issues"
license="GNU LESSER GENERAL PUBLIC LICENSE"

[[mods]]
    modId="ma-enchants"
    version="${file.jarVersion}"
    displayName="Ma Enchants"
    updateJSONURL="https://raw.githubusercontent.com/Maciej916/Ma-Enchants/1.16/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/ma-enchants"
    logoFile="ma-enchants.png"
    credits=""
    authors="Maciej916"
    description="Multiple new enchants and curses"

    [[dependencies.maenchants]]
        modId="forge"
        mandatory=true
        versionRange="[36.0.0,)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.maenchants]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.5]"
        ordering="NONE"
        side="BOTH"