modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Maciej916/Ma-Enchants/issues"

[[mods]]
    modId="ma-enchants"
    version="${file.jarVersion}"
    displayName="Ma Enchants"
    updateJSONURL="https://raw.githubusercontent.com/Maciej916/Ma-Enchants/1.16/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/ma-enchants"
    logoFile="ma-enchants.png"
    credits=""
    authors="Statywek (Maciej916)"
    description="Multiple new enchants and curses"

    [[dependencies.maenchants]]
        modId="forge"
        mandatory=true
        versionRange="[32.0.1,)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.maenchants]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.1]"
        ordering="NONE"
        side="BOTH"